"""Add is_starred to Product model

Revision ID: 28522ef8442a
Revises: deee4e4f36d5
Create Date: 2024-10-21 19:44:33.653045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28522ef8442a'
down_revision = 'deee4e4f36d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_starred', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_starred')

    # ### end Alembic commands ###
