"""Add description to Category

Revision ID: 536c42a4d525
Revises: 8c9539d23cf1
Create Date: 2024-11-05 23:25:06.890858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536c42a4d525'
down_revision = '8c9539d23cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
